//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEEAppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderDetail
    {
        public int Id { get; set; }
        public string ReminderText { get; set; }
        public System.DateTime ReminderTime { get; set; }
        public int OwnerId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
